# Railway Configuration for Frontend Service ONLY
# This file should be used when deploying Frontend as a separate service

[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd frontend && vite preview --host 0.0.0.0 --port $PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = [
  'cd frontend',
  'pnpm install'
]

[phases.build]
cmds = [
  'cd frontend',
  'pnpm run build'
]

