[build]
builder = "NIXPACKS"
workingDir = "frontend"

[deploy]
startCommand = "vite preview --host 0.0.0.0 --port $PORT"

[phases.setup]
nixPkgs = ['nodejs_20', 'pnpm']

[phases.install]
cmds = ['pnpm install']

[phases.build]
cmds = ['pnpm run build']

